export enum RATE_LIMIT_ALGO_TYPE {
  TOKEN_BUCKET = "TOCKEN_BUCKET",
  FIXED_WINDOW_COUNTER = "FIXED_WINDOW_COUNTER",
  TUMBLING_WINDOW_COUNTER = "TUMBLING_WINDOW_COUNTER",
  SLIDING_WINDOW_LOG = "SLIDING_WINDOW_LOG",
  SLIDING_WINDOW_COUNTER = "SLIDING_WINDOW_COUNTER",
}
